
import java.sql.*;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author enric
 */
public class editPenyewa extends javax.swing.JFrame {

    /**
     * Creates new form editPenyewa
     */
    public editPenyewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_penyewa = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        tomboltambah = new javax.swing.JButton();
        tombolhapus = new javax.swing.JButton();
        tomboledit = new javax.swing.JButton();
        tombolcari = new javax.swing.JButton();
        tombolrefresh = new javax.swing.JButton();
        tombolkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengolahan Database Penyewaan Kendaraan");

        tabel_penyewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id_penyewa", "nama_penyewa", "no_telp"
            }
        ));
        jScrollPane1.setViewportView(tabel_penyewa);

        jLabel1.setText("Tabel Penyewa");

        tomboltambah.setText("Tambah");
        tomboltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltambahActionPerformed(evt);
            }
        });

        tombolhapus.setText("Hapus");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        tomboledit.setText("Edit");
        tomboledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboleditActionPerformed(evt);
            }
        });

        tombolcari.setText("Cari");
        tombolcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcariActionPerformed(evt);
            }
        });

        tombolrefresh.setText("Refresh");
        tombolrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolrefreshActionPerformed(evt);
            }
        });

        tombolkembali.setText("Kembali");
        tombolkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolcari, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tomboltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tombolrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombolrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tomboltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tombolkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkembaliActionPerformed
        // TODO add your handling code here:
        dispose();
        
        menuForm menu = new menuForm();
        menu.setVisible(true);
    }//GEN-LAST:event_tombolkembaliActionPerformed

    private void tombolrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolrefreshActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
            
            ResultSet rs = st.executeQuery("SELECT * FROM Penyewa;");
            DefaultTableModel tm=(DefaultTableModel)tabel_penyewa.getModel();
            tm.setRowCount(0);
            while(rs.next())
            {
                Object o[]={rs.getInt("id_penyewa"),rs.getString("nama_penyewa"),
                    rs.getString("no_telp")};
                    tm.addRow(o);
            }       

            st.close();
            conn.close();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal refresh");
            } catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tombolrefreshActionPerformed

    private void tomboltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltambahActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
        
            String nama_penyewa = JOptionPane.showInputDialog("Masukan Nama Penyewa");
            String no_telp = JOptionPane.showInputDialog("Masukan Nomor Telepon");
            
            if(nama_penyewa == null || no_telp == null)
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Ditambah");
            }
            else
            {
                String sql ="insert into Penyewa(nama_penyewa,no_telp) values (?,?)";
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,nama_penyewa);
                ps.setString(2,no_telp);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah, Silahkan Klik Tombol Refresh");
            }
                st.close();
                conn.close();     
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Ditambah");
            } catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tomboltambahActionPerformed

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
            
            int column = 0;
            int row = tabel_penyewa.getSelectedRow();
            int id_penyewa = (int) tabel_penyewa.getModel().getValueAt(row, 0);
            
            if (JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) 
            {
                String sql ="DELETE FROM penyewa WHERE id_penyewa = "+id_penyewa+";";
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            } 
            else 
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
            }
            st.close();
            conn.close();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
            } catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }        
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tomboleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboleditActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
            
            int column = 0;
            int row = tabel_penyewa.getSelectedRow();
            int id_penyewa = (int) tabel_penyewa.getModel().getValueAt(row, 0);
            
            String nama_penyewa = JOptionPane.showInputDialog("Masukan Nama Penyewa");
            String no_telp = JOptionPane.showInputDialog("Masukan Nomor Telepon");
            
            if (nama_penyewa == null || no_telp == null) 
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");                
            } 
            else 
            {
                String sql ="UPDATE penyewa SET nama_penyewa = (?) , no_telp = (?) WHERE id_penyewa ="+id_penyewa+";";
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setString(1,nama_penyewa);
                ps.setString(2,no_telp);                
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");
            }
            st.close();
            conn.close();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            } catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tomboleditActionPerformed

    private void tombolcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcariActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
           
            JTextField id = new JTextField(10);    
            JTextField nama = new JTextField(20);
            JTextField telp = new JTextField(12);
            
            JPanel cari = new JPanel();
            cari.setLayout(new BoxLayout(cari, BoxLayout.PAGE_AXIS));
            cari.setBorder(BorderFactory.createEmptyBorder(0, 10, 10, 10));
            cari.add(new JLabel("ID Penyewa:"));
            cari.add(id);
            cari.add(Box.createVerticalGlue()); // a spacer
            cari.add(new JLabel("Nama Penyewa:"));
            cari.add(nama);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Nomor Telepon :"));
            cari.add(telp);
            
            int result = JOptionPane.showConfirmDialog(null, cari, 
            "Masukan Data Yang Ingin Di Cari", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION) 
            {
                ResultSet rs = st.executeQuery("SELECT * From Penyewa WHERE id_penyewa "
                        + "LIKE '%"+id.getText()+"%' "
                        + "AND nama_penyewa LIKE '%"+nama.getText()+"%' "
                        + "AND no_telp LIKE '%"+telp.getText()+"%';");
                DefaultTableModel tm=(DefaultTableModel)tabel_penyewa.getModel();
                tm.setRowCount(0);
                while(rs.next())
                {
                    Object o[]={rs.getInt("id_penyewa"),rs.getString("nama_penyewa"),
                        rs.getString("no_telp")};
                        tm.addRow(o);
                }       
            }
            st.close();
            conn.close();
            }
            catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Data Tidak Ditemukan");
            } catch(ClassNotFoundException e){
                JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }        
    }//GEN-LAST:event_tombolcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            }UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editPenyewa().setVisible(true);
            }   
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_penyewa;
    private javax.swing.JButton tombolcari;
    private javax.swing.JButton tomboledit;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tombolkembali;
    private javax.swing.JButton tombolrefresh;
    private javax.swing.JButton tomboltambah;
    // End of variables declaration//GEN-END:variables

    private String setString(boolean execute) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
