/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author enric
 */
public class editSewa extends javax.swing.JFrame {

    /**
     * Creates new form editSewa
     */
    public editSewa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabel_sewa = new javax.swing.JTable();
        tomboltambah = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tomboledit = new javax.swing.JButton();
        tombolhapus = new javax.swing.JButton();
        tombolcari = new javax.swing.JButton();
        tombolrefresh = new javax.swing.JButton();
        tombolkembali = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pengolahan Database Penyewaan Kendaraan");

        tabel_sewa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "no_sewa", "id_penyewa", "id_petugas", "tgl_sewa", "tgl_kembali", "tgl_transaksi", "lama_transaksi", "nomor_polisi", "harga_sewa"
            }
        ));
        jScrollPane1.setViewportView(tabel_sewa);

        tomboltambah.setText("Tambah");
        tomboltambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboltambahActionPerformed(evt);
            }
        });

        jLabel1.setText("Tabel Sewa");

        tomboledit.setText("Edit");
        tomboledit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tomboleditActionPerformed(evt);
            }
        });

        tombolhapus.setText("Hapus");
        tombolhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolhapusActionPerformed(evt);
            }
        });

        tombolcari.setText("Cari");
        tombolcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolcariActionPerformed(evt);
            }
        });

        tombolrefresh.setText("Refresh");
        tombolrefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolrefreshActionPerformed(evt);
            }
        });

        tombolkembali.setText("Kembali");
        tombolkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolkembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 766, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolcari, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tomboltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tombolrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
            .addGroup(layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tombolrefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tomboltambah, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(tombolhapus, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tomboledit, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolcari, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tombolkembali, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tomboltambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboltambahActionPerformed
        // TODO add your handling code here:
        try{
            JComboBox pnyw = new JComboBox();
            JComboBox ptgs = new JComboBox();
            JComboBox nmr_pls = new JComboBox();
            JTextField tgl_sewa = new JTextField(15);
            JTextField tgl_kembali = new JTextField(15);
            JTextField tgl_transaksi = new JTextField(15);
            
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
            Statement dt = conn.createStatement(); 
            Statement bt = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from penyewa;");
            ResultSet ds = dt.executeQuery("Select * from Petugas");
            ResultSet bs = bt.executeQuery("Select * from mobil");

            JPanel tambah = new JPanel();
            tambah.setLayout(new BoxLayout(tambah, BoxLayout.PAGE_AXIS));
            tambah.add(new JLabel("Format Tanggal YYYY-MM-DD"));
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Sewa"));
            tambah.add(tgl_sewa);
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Kembali"));
            tambah.add(tgl_kembali); 
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Transaksi"));
            tambah.add(tgl_transaksi);
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Id Penyewa:"));
            while(rs.next())
            {
                pnyw.addItem(rs.getInt("id_penyewa")+" - "+rs.getString("nama_penyewa"));
                tambah.add(pnyw);            
            }
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Id Petugas:"));
            
            while(ds.next())
            {
                ptgs.addItem(ds.getInt("id_petugas")+" - "+ds.getString("nama_petugas"));
                tambah.add(ptgs);
            }
            
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Nomor Polisi:"));            
            while(bs.next())
            {
                nmr_pls.addItem(bs.getString("nomor_polisi"));
                tambah.add(nmr_pls);
            }
            
            int result = JOptionPane.showConfirmDialog(null, tambah,
            "Pilih Kode Merek", JOptionPane.OK_CANCEL_OPTION);
            
            String id_pnyw = pnyw.getSelectedItem().toString();
            int id_penyewa = Integer.parseInt(id_pnyw.replaceAll("\\D+",""));
            String id_ptgs = ptgs.getSelectedItem().toString();
            int id_petugas = Integer.parseInt(id_ptgs.replaceAll("\\D+",""));
            String nomor_polisi = nmr_pls.getSelectedItem().toString();
            
            if (result == JOptionPane.OK_OPTION)
            {
                String query ="insert into sewa(id_penyewa,id_petugas,tgl_sewa,tgl_kembali,tgl_transaksi,nomor_polisi) values (?,?,?,?,?,?)";
                PreparedStatement ps=conn.prepareStatement(query);
                ps.setInt(1,id_penyewa);
                ps.setInt(2,id_petugas);
                ps.setString(3,tgl_sewa.getText());
                ps.setString(4,tgl_kembali.getText());
                ps.setString(5,tgl_transaksi.getText());
                ps.setString(6, nomor_polisi);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Ditambah, Silahkan Klik Tombol Refresh");
            }
            st.close();
            conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Dalam Memproses");
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tomboltambahActionPerformed

    private void tomboleditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tomboleditActionPerformed
        // TODO add your handling code here:
        try{
            JComboBox pnyw = new JComboBox();
            JComboBox ptgs = new JComboBox();
            JComboBox nmr_pls = new JComboBox();
            JTextField tgl_sewa = new JTextField(15);
            JTextField tgl_kembali = new JTextField(15);
            JTextField tgl_transaksi = new JTextField(15);
            
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();
            Statement dt = conn.createStatement(); 
            Statement bt = conn.createStatement();
            ResultSet rs = st.executeQuery("Select * from penyewa;");
            ResultSet ds = dt.executeQuery("Select * from Petugas");
            ResultSet bs = bt.executeQuery("Select * from mobil");

            JPanel tambah = new JPanel();
            tambah.setLayout(new BoxLayout(tambah, BoxLayout.PAGE_AXIS));
            tambah.add(new JLabel("Format Tanggal YYYY-MM-DD"));
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Sewa"));
            tambah.add(tgl_sewa);
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Kembali"));
            tambah.add(tgl_kembali); 
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Tanggal Transaksi"));
            tambah.add(tgl_transaksi);
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Id Penyewa:"));
            while(rs.next())
            {
                pnyw.addItem(rs.getInt("id_penyewa")+" - "+rs.getString("nama_penyewa"));
                tambah.add(pnyw);            
            }
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Id Petugas:"));
            
            while(ds.next())
            {
                ptgs.addItem(ds.getInt("id_petugas")+" - "+ds.getString("nama_petugas"));
                tambah.add(ptgs);
            }
            
            tambah.add(Box.createVerticalGlue());
            tambah.add(new JLabel("Nomor Polisi:"));            
            while(bs.next())
            {
                nmr_pls.addItem(bs.getString("nomor_polisi"));
                tambah.add(nmr_pls);
            }
            
            int result = JOptionPane.showConfirmDialog(null, tambah,
            "Pilih Kode Merek", JOptionPane.OK_CANCEL_OPTION);
            
            String id_pnyw = pnyw.getSelectedItem().toString();
            int id_penyewa = Integer.parseInt(id_pnyw.replaceAll("\\D+",""));
            String id_ptgs = ptgs.getSelectedItem().toString();
            int id_petugas = Integer.parseInt(id_ptgs.replaceAll("\\D+",""));
            String nomor_polisi = nmr_pls.getSelectedItem().toString();
            int column = 0;
            int row = tabel_sewa.getSelectedRow();
            int no_sewa = (int) tabel_sewa.getModel().getValueAt(row, 0);

            if(id_penyewa == 0 || id_petugas == 0 || tgl_sewa == null || 
                    tgl_kembali == null || tgl_transaksi == null || nomor_polisi == null)
            {
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah");
            }
            else
            {
                String sql = ("UPDATE `sewa` SET  `id_penyewa` = (?) , "
                        + "`id_petugas` = (?) , `tgl_sewa` = (?) , "
                        + "`tgl_kembali` = (?) , `tgl_transaksi` = (?) , "
                        + "`nomor_polisi` = (?) WHERE `no_sewa` = '"+no_sewa+"';");
                PreparedStatement ps=conn.prepareStatement(sql);
                ps.setInt(1,id_penyewa);
                ps.setInt(2,id_petugas);
                ps.setString(3,tgl_sewa.getText());
                ps.setString(4,tgl_kembali.getText());
                ps.setString(5,tgl_transaksi.getText());
                ps.setString(6, nomor_polisi);
                ps.execute();
                JOptionPane.showMessageDialog(null, "Data Berhasil Diubah, Silahkan Klik Tombol Refresh");
            }
            st.close();
            conn.close();

        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Dalam Pemrosesan");
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tomboleditActionPerformed

    private void tombolhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolhapusActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();

            int column = 0;
            int row = tabel_sewa.getSelectedRow();
            String no_sewa = tabel_sewa.getModel().getValueAt(row, 0).toString();

            if (JOptionPane.showConfirmDialog(null, "Apakah Kamu Yakin?", "Konfirmasi",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)
        {
            String sql ="DELETE FROM sewa WHERE no_sewa = '"+no_sewa+"';";
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.execute();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus, Silahkan Klik Tombol Refresh");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Data Gagal Dihapus");
        }
        st.close();
        conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Dalam Pemrosesan");
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tombolhapusActionPerformed

    private void tombolcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolcariActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();

            JTextField no_sewa = new JTextField(10);
            JTextField id_penyewa = new JTextField(10);
            JTextField id_petugas = new JTextField(10);
            JTextField nomor_polisi = new JTextField(12);
            JTextField tgl_sewa = new JTextField(15);
            JTextField tgl_kembali = new JTextField(15);
            JTextField tgl_transaksi = new JTextField(15); 
            JTextField lama_sewa = new JTextField(10);
            JTextField harga_sewa = new JTextField(16);
            
            JPanel cari = new JPanel();
            cari.setLayout(new BoxLayout(cari, BoxLayout.PAGE_AXIS));
            cari.add(new JLabel("Format Tanggal YYYY-MM-DD"));
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("No Sewa"));
            cari.add(no_sewa);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Id Penyewa:"));
            cari.add(id_penyewa);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Id Petugas"));
            cari.add(id_petugas);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Tanggal Sewa"));
            cari.add(tgl_sewa);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Tanggal Kembali"));
            cari.add(tgl_kembali); 
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Tanggal Transaksi"));
            cari.add(tgl_transaksi);         
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Lama Sewa"));
            cari.add(lama_sewa);
            cari.add(Box.createVerticalGlue());            
            cari.add(new JLabel("Nomor Polisi"));
            cari.add(nomor_polisi);
            cari.add(Box.createVerticalGlue());
            cari.add(new JLabel("Harga Sewa"));
            cari.add(harga_sewa);
            
            int result = JOptionPane.showConfirmDialog(null, cari,
                "Masukan Data Yang Ingin Di Cari", JOptionPane.OK_CANCEL_OPTION);
            if (result == JOptionPane.OK_OPTION)
            {
                ResultSet rs = st.executeQuery("SELECT * From sewa WHERE no_sewa "
                    + "LIKE '%"+no_sewa.getText()+"%' AND "
                    + "id_penyewa LIKE '%"+id_penyewa.getText()+"%' AND "
                    + "id_petugas LIKE '%"+id_petugas.getText()+"%' AND "
                    + "tgl_sewa LIKE '%"+tgl_sewa.getText()+"%' AND "
                    + "tgl_kembali LIKE '%"+tgl_kembali.getText()+"%' AND "
                    + "tgl_transaksi LIKE '%"+tgl_transaksi.getText()+"%' AND "
                    + "lama_sewa LIKE '%"+lama_sewa.getText()+"%' AND "
                    + "nomor_polisi LIKE '%"+nomor_polisi.getText()+"%' "                            
                    + "AND harga_sewa LIKE '%"+harga_sewa.getText()+"%';");
                DefaultTableModel tm=(DefaultTableModel)tabel_sewa.getModel();
                tm.setRowCount(0);
                while(rs.next())
                {
                    Object o[]={rs.getInt("no_sewa"),rs.getInt("id_penyewa"),
                    rs.getInt("id_petugas"),rs.getDate("tgl_sewa"),rs.getDate("tgl_kembali"),
                    rs.getDate("tgl_transaksi"),rs.getInt("lama_sewa"),rs.getString("nomor_polisi"),
                    rs.getInt("harga_sewa")};
                    tm.addRow(o);
                }
            }
            st.close();
            conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Dalam Pemrosesan");
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tombolcariActionPerformed

    private void tombolrefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolrefreshActionPerformed
        // TODO add your handling code here:
        try{
            String user = "root";
            String pass = "";
            String dbURL = "jdbc:mysql://localhost/db10118295penyewaankendaraan";
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection(dbURL, user, pass);
            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery("SELECT * FROM Sewa;");
            DefaultTableModel tm=(DefaultTableModel)tabel_sewa.getModel();
            tm.setRowCount(0);
            PreparedStatement cs=conn.prepareStatement("UPDATE sewa SET lama_sewa = tgl_kembali - tgl_sewa;");
            cs.execute();
            PreparedStatement ks=conn.prepareStatement("UPDATE sewa SET "
                + "harga_sewa = lama_sewa * (SELECT biaya_mobil "
                + "FROM tipe_mobil INNER JOIN mobil ON mobil.`kode_tipe` = "
                + "tipe_mobil.`kode_tipe` WHERE mobil.`nomor_polisi`=sewa.`nomor_polisi`);");
            ks.execute();
            while(rs.next())
            {
                Object o[]={rs.getInt("no_sewa"),rs.getInt("id_penyewa"),
                    rs.getInt("id_petugas"),rs.getDate("tgl_sewa"),rs.getDate("tgl_kembali"),
                    rs.getDate("tgl_transaksi"),rs.getInt("lama_sewa"),rs.getString("nomor_polisi"),
                    rs.getInt("harga_sewa")};
                tm.addRow(o);
            }
            
            st.close();
            conn.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Dalam Pemrosesan");
        } catch(ClassNotFoundException e){
            JOptionPane.showMessageDialog(null, "JDBC Driver tidak ditemukan");
        }
    }//GEN-LAST:event_tombolrefreshActionPerformed

    private void tombolkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolkembaliActionPerformed
        // TODO add your handling code here:
        dispose();

        menuForm menu = new menuForm();
        menu.setVisible(true);
    }//GEN-LAST:event_tombolkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            }UIManager.setLookAndFeel("com.jtattoo.plaf.hifi.HiFiLookAndFeel");
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new editSewa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel_sewa;
    private javax.swing.JButton tombolcari;
    private javax.swing.JButton tomboledit;
    private javax.swing.JButton tombolhapus;
    private javax.swing.JButton tombolkembali;
    private javax.swing.JButton tombolrefresh;
    private javax.swing.JButton tomboltambah;
    // End of variables declaration//GEN-END:variables
}
